question_data = [
 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
  "question": "In &quot;The Sims&quot; series, the most members in a household you can have is 8.",
  "correct_answer": "True", "incorrect_answers": ["False"]},

 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
  "question": "Tetris is the #1 best-selling video game of all-time.",
  "correct_answer": "False", "incorrect_answers": ["True"]},
 {"category": "Entertainment: Video Games", "type": "boolean",
  "difficulty": "medium",
  "question": "In World of Warcraft lore, Thrall is the original wielder of &quot;Doomhammer&quot;.",
  "correct_answer": "False", "incorrect_answers": ["True"]},
 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
  "question": "Solid Snake is actually a clone from the DNA of Big Boss in the Metal Gear Solid series&#039; history.",
  "correct_answer": "True", "incorrect_answers": ["False"]},
 {"category": "Entertainment: Video Games", "type": "boolean",
  "difficulty": "medium",
  "question": "TF2: The Heavy&#039;s voice actor, Gary Schwartz, voices the Demoman as well ",
  "correct_answer": "True", "incorrect_answers": ["False"]},
 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
  "question": "The names of Roxas&#039;s Keyblades in Kingdom Hearts are &quot;Oathkeeper&quot; and &quot;Oblivion&quot;.",
  "correct_answer": "True", "incorrect_answers": ["False"]},
 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
  "question": "In Terraria, you can craft the Cell Phone pre-hardmode.",
  "correct_answer": "True", "incorrect_answers": ["False"]},
 {"category": "Entertainment: Video Games", "type": "boolean",
  "difficulty": "medium",
  "question": "Pistons were added to Minecraft in Beta 1.5.",
  "correct_answer": "False", "incorrect_answers": ["True"]},
 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
  "question": "The Konami Code is known as Up, Up, Down, Down, Left, Right, Right, Left, B, A, Start.",
  "correct_answer": "False", "incorrect_answers": ["True"]},
 {"category": "Entertainment: Video Games", "type": "boolean",
  "difficulty": "medium",
  "question": "David Baszucki was a co-founder of ROBLOX Corporation.",
  "correct_answer": "True", "incorrect_answers": ["False"]},
 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
  "question": "All of these maps were in &quot;Tom Clancy&#039;s Rainbow Six Siege&quot; on its initial release: House, Clubhouse, Border, Consulate.",
  "correct_answer": "False", "incorrect_answers": ["True"]},
 {"category": "Entertainment: Video Games", "type": "boolean",
  "difficulty": "medium",
  "question": "In the video game &quot;Transistor&quot;, &quot;Red&quot; is the name of the main character.",
  "correct_answer": "True", "incorrect_answers": ["False"]},
 {"category": "Entertainment: Video Games", "type": "boolean",
  "difficulty": "medium",
  "question": "In &quot;Call Of Duty: Zombies&quot;, you can upgrade the &quot;Apothicon Servant&quot; in the &quot;Shadows Of Evil&quot; map.",
  "correct_answer": "False", "incorrect_answers": ["True"]},
 {"category": "Entertainment: Video Games", "type": "boolean",
  "difficulty": "medium",
  "question": "In &quot;League of Legends&quot;, there exists four different types of Dragon.",
  "correct_answer": "False", "incorrect_answers": ["True"]},
 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
  "question": "Several characters in &quot;Super Mario 64&quot; blink their eyes, including Mario himself.",
  "correct_answer": "True", "incorrect_answers": ["False"]},
 {"category": "Entertainment: Video Games", "type": "boolean",
  "difficulty": "medium",
  "question": "The scrapped Sonic the Hedgehog 2 level &quot;Hidden Palace Zone&quot; was later reused in the iOS port of the game. ",
  "correct_answer": "True", "incorrect_answers": ["False"]},
 {"category": "Entertainment: Video Games", "type": "boolean",
  "difficulty": "medium",
  "question": "In the game &quot;Until Dawn&quot; Emily is the only playable character who can be killed by another playable character directly.",
  "correct_answer": "True", "incorrect_answers": ["False"]},
 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
  "question": "There are 2 player roles in Trouble in Terrorist Town.",
  "correct_answer": "False", "incorrect_answers": ["True"]},
 {"category": "Entertainment: Video Games", "type": "boolean",
  "difficulty": "medium",
  "question": "Shang Tsung is a playable character in Mortal Kombat XL.",
  "correct_answer": "False", "incorrect_answers": ["True"]},
 {"category": "Entertainment: Video Games", "type": "boolean",
  "difficulty": "medium",
  "question": "In the Resident Evil series, Leon S. Kennedy is a member of STARS.",
  "correct_answer": "False", "incorrect_answers": ["True"]}
 ]
